name: "Set Env"
description: "This action is used to set env. variables from github secrets and variables"
inputs:
  secrets:
    description: 'Set this input to toJson(secrets)'
    required: true
runs:
  using: "composite"
  steps:
    - name: view the secrets context
      shell: bash
      run: echo "${{ inputs.secrets }}"
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: setenv.sh
      env:
        SECRETS_CONTEXT: ${{ inputs.secrets }}
      shell: bash
