name: Checkout Files

on:
  workflow_dispatch:

jobs:
  checkout-files:
    name: Re-tag and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: package.json checkout-files
